ByteArray class for primary keys with byte[]
ydb-platform/yoj-project pull request #17
Opened 2024-02-01 17:44 UTC by lavrukov

Byte arrays in primary keys support.

We can't do it with simple byte[], because records default comparator and equals uses compare adresses, not real data. Special class for this looks better, than magic over byte[]

2024-02-01 17:45 UTC, lavrukov commented on databind/src/main/java/tech/ydb/yoj/databind/ByteArray.java
> +    // TODO: check that YDB have the same compare
I will fix in in next commit

2024-02-02 15:15 UTC, nvamelichev requested changes
Overall very good!

I request some minor improvements
- Add another (convenience) copy constructor to `ByteArray`, it will make the test so much nicer:
```java
var copy = ByteArray.copy(ba); // copies ByteArray's bytes :-)
var copy2 = ba.copy(); // same as ByteArray.copy(ba), just alternative syntax
```
- Add tests for `ByteArray`-keyed entities to `ListingTest` and `TableQueryBuilderTest` (to test `Table.list()` and `Table.query()` DSL explicitly)

Other than that, I think the PR is great!

2024-02-02 15:15 UTC, nvamelichev commented on databind/src/main/java/tech/ydb/yoj/databind/expression/ModelField.java
> +                    p -> format("Specified a boolean value for non-boolean field \"%s\"", p));
Typo: "**boolean** value", "non-**boolean** field" instead of "ByteArray value", "non-ByteArray field"

2024-02-14 19:45 UTC, nvamelichev approved these changes
Merging! :tada:

2024-02-14 19:46 UTC, merged