main: FieldValue interface
ydb-platform/yoj-project pull request #75
Opened 2024-06-01 20:01 UTC by lavrukov

2024-06-14 12:46 UTC, nvamelichev requested changes

2024-06-14 16:53 UTC, lavrukov commented on databind/src/main/java/tech/ydb/yoj/databind/expression/values/BoolFieldValue.java
> +public record BoolFieldValue(
It's good Idea, but I don't know how to solve name collision like ByteArray, and Tuple

2024-06-24 16:17 UTC, nvamelichev commented
@lavrukov Please fix minor checkstyle failures:
```
Error:  /home/runner/work/yoj-project/yoj-project/databind/src/main/java/tech/ydb/yoj/databind/expression/values/RealFieldValue.java:13:36: 'switch' is not preceded with whitespace. [WhitespaceAround]
Error:  /home/runner/work/yoj-project/yoj-project/databind/src/main/java/tech/ydb/yoj/databind/expression/values/TimestampFieldValue.java:14:36: 'switch' is not preceded with whitespace. [WhitespaceAround]
Error:  /home/runner/work/yoj-project/yoj-project/databind/src/main/java/tech/ydb/yoj/databind/expression/values/NumberFieldValue.java:14:36: 'switch' is not preceded with whitespace. [WhitespaceAround]
Error:  /home/runner/work/yoj-project/yoj-project/databind/src/main/java/tech/ydb/yoj/databind/expression/values/FieldValue.java:37:1: '{' at column 1 should be on the previous line. [LeftCurly]
Error:  /home/runner/work/yoj-project/yoj-project/databind/src/main/java/tech/ydb/yoj/databind/expression/values/StringFieldValue.java:16:36: 'switch' is not preceded with whitespace. [WhitespaceAround]
```

and this will be ready to merge, I think :-)

2024-09-02 18:19 UTC, nvamelichev commented
TODO: Move FieldValue interface a package up (to where it was) for better compatibility

2024-09-03 11:27 UTC, nvamelichev commented
**UPD:** Brought back compatibility `FieldValue` interface in old package (with deprecation warnings, of course!)

2024-09-03 15:33 UTC, nvamelichev commented
@lavrukov Sasha, please look at this. I've made the `FieldValue` interface a bit more backwards-compatible then before, for a smooth transition :-)

(And we'll still release this as the next major version, 2.**6**.0)

2024-10-04 17:19 UTC, lavrukov commented on databind/src/main/java/tech/ydb/yoj/databind/expression/values/BooleanFieldValue.java
> +package tech.ydb.yoj.databind.expression.values;
nit: maybe name package like `fieldvalue` ?

2024-10-04 17:31 UTC, lavrukov commented on databind/src/main/java/tech/ydb/yoj/databind/expression/ModelField.java
> +        if (value instanceof TupleFieldValue tupleValue) {
logic under instanceof for interface looks little bit strange. Maybe it possible to make part of interface?
```
if(!value.check(fieldValueType)) {
    if (userFieldPath != null) {
         throw value.buildUserException(userFieldPath)
    } else {
        throw new IllegalArgumentException("formatted message")
    }
}

```

2024-10-05 18:46 UTC, lavrukov commented on databind/src/main/java/tech/ydb/yoj/databind/expression/values/ByteArrayFieldValue.java
> +        return "byte array with hash " + hashCode();
we did it beacause there could be a private data, ifiar

2024-10-07 17:46 UTC, nvamelichev approved these changes

2024-10-07 17:46 UTC, nvamelichev commented on databind/src/main/java/tech/ydb/yoj/databind/expression/values/NumberFieldValue.java
> +public record NumberFieldValue(
:heavy_check_mark: renamed, actually

2024-10-07 17:46 UTC, nvamelichev commented on databind/src/main/java/tech/ydb/yoj/databind/expression/values/ByteArrayFieldValue.java
> +        return "byte array with hash " + hashCode();
OK, that's not a big deal, and if someone needs more informative `ByteArrayFieldValue.toString()` we can always reconsider

2024-10-10 11:08 UTC, merged